version: '3'
services:
  db:
    image: postgres:15.4
    container_name: my-postgres-container
    environment:
       POSTGRES_USER: myuser
       POSTGRES_PASSWORD: mypassword
       POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    
